In [1]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#### Numpy Installation : pip install numpy or conda install numpy

# 1. Matrix

### 1.1 Create matrix

In [31]:
mat = np.matrix([1,2])
print(mat)

[[1 2]]


In [5]:
mat = np.matrix('1,2; 3,4')
print(mat)

[[1 2]
 [3 4]]


In [9]:
import numpy.matlib 
print(np.matlib.zeros((2,2))) 

[[0. 0.]
 [0. 0.]]
<class 'numpy.matrix'>


In [10]:
print(np.matlib.ones((2,2)))

[[1. 1.]
 [1. 1.]]


In [12]:
print(np.matlib.eye(4, 4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
print(np.matlib.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
print(np.matlib.rand(3,3))

[[0.9921978  0.14304082 0.77939147]
 [0.92285105 0.97766522 0.43299091]
 [0.14945232 0.42105921 0.34135818]]


In [17]:
rand = np.matlib.randn(10)
print(rand)

[[ 0.54245533 -1.69023482  1.00632481  0.9948155   0.9685877  -0.16519509
   0.48217895  0.01917634  0.11427815 -0.06612495]]
<class 'numpy.matrix'>


In [28]:
k = [[1,2],[3,4]]
mat = np.asmatrix(k)
print(mat)

<class 'numpy.matrix'>
[[1 2]
 [3 4]]


In [30]:
name = "1,2; 3,4"
mat = np.asmatrix(name)
print(mat)

[[1 2]
 [3 4]]


### 1.2 Funtion/Feature

In [37]:
mat = np.matrix('1,2; 3,4')
print(mat)

[[1 2]
 [3 4]]


In [33]:
print(type(mat))

<class 'numpy.matrix'>


In [34]:
print(mat.size)

2


In [35]:
print(len(mat))

1


In [38]:
print(mat.dtype)

int32


In [39]:
print(mat.reshape(4,1))

[[1]
 [2]
 [3]
 [4]]


In [40]:
print(mat.shape)

(2, 2)


In [ ]:
# Updating 